# Generated by Django 4.0.4 on 2022-06-17 17:30

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('subscription', models.BooleanField(default=False, verbose_name='Подписан?')),
                ('subscription_email', models.EmailField(blank=True, max_length=256, null=True, verbose_name='Почта подписки')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdBigPhotoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='ad_big_photo_images/', verbose_name='Фото')),
                ('ad_period', models.DateField(blank=True, null=True, verbose_name='Срок рекламы')),
                ('published', models.BooleanField(verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Большая реклама',
                'verbose_name_plural': 'Большие рекламы',
            },
        ),
        migrations.CreateModel(
            name='AdSmallPhotoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='ad_small_photo_images/', verbose_name='Фото')),
                ('ad_period', models.DateField(blank=True, null=True, verbose_name='Срок рекламы')),
                ('published', models.BooleanField(verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Маленькая реклама',
                'verbose_name_plural': 'Маленькие рекламы',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Купон')),
                ('validity_period', models.DateField(blank=True, null=True, verbose_name='Срок действия')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('percent', models.IntegerField(blank=True, null=True, verbose_name='Процент')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купоны',
            },
        ),
        migrations.CreateModel(
            name='DirectionEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_effect_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Направление воздействияэффекта')),
            ],
            options={
                'verbose_name': 'Направление воздействия эффекта',
                'verbose_name_plural': 'Направления воздействий эффектов',
            },
        ),
        migrations.CreateModel(
            name='Moods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Настроение')),
            ],
            options={
                'verbose_name': 'Настроение',
                'verbose_name_plural': 'Настроения',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_begin', models.TimeField(blank=True, null=True, verbose_name='Начало хронометража')),
                ('time_end', models.TimeField(blank=True, null=True, verbose_name='Конец хронометража')),
                ('beginning_peak', models.BooleanField(verbose_name='Пик в начале')),
                ('ending', models.BooleanField(verbose_name='Окончание плавное')),
                ('is_auto_layout', models.BooleanField(verbose_name='Автоматическая компоновка?')),
                ('comment_for_product', models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий к продукту')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderSegmentAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_add_begin', models.TimeField(blank=True, null=True, verbose_name='Начало хронометража')),
                ('time_add_end', models.TimeField(blank=True, null=True, verbose_name='Конец хронометража')),
                ('time_insert', models.TimeField(blank=True, null=True, verbose_name='Вставить в')),
            ],
            options={
                'verbose_name': 'Таймер добавления',
                'verbose_name_plural': 'Таймеры добавлений',
            },
        ),
        migrations.CreateModel(
            name='OrderSegmentDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_delete_begin', models.TimeField(blank=True, null=True, verbose_name='Начало хронометража')),
                ('time_delete_end', models.TimeField(blank=True, null=True, verbose_name='Конец хронометража')),
            ],
            options={
                'verbose_name': 'Таймер удаления',
                'verbose_name_plural': 'Таймеры удалений',
            },
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Наименование спорта')),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Виды спорта',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Хэштег')),
            ],
            options={
                'verbose_name': 'Хэштег',
                'verbose_name_plural': 'Хэштеги',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='mp4', verbose_name='Трэк')),
                ('photo', models.ImageField(upload_to='track_images/', verbose_name='Фото')),
                ('author', models.CharField(blank=True, max_length=150, null=True, verbose_name='Автор')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название трека')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('track_length', models.IntegerField(blank=True, null=True, verbose_name='Длительность трека')),
                ('with_words', models.BooleanField(default=False, verbose_name='Со словами?')),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzsport.country', verbose_name='Страна')),
                ('mood_name', models.ManyToManyField(to='muzsport.moods', verbose_name='Настроение')),
                ('sports_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzsport.sports', verbose_name='Наименование спорта')),
                ('tag_name', models.ManyToManyField(to='muzsport.tags', verbose_name='Хэштег')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
            },
        ),
        migrations.CreateModel(
            name='UnloadingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на файл')),
                ('file', models.FileField(blank=True, null=True, upload_to='mp4', verbose_name='Дополнительный файл')),
                ('direction_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzsport.directioneffect', verbose_name='Направление воздействияэффекта')),
            ],
            options={
                'verbose_name': 'Суггестивный эффект',
                'verbose_name_plural': 'Суггестивные эффекты',
            },
        ),
        migrations.CreateModel(
            name='SuggestiveEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя спортсмена')),
                ('file', models.FileField(blank=True, null=True, upload_to='mp4', verbose_name='Дополнительный файл')),
                ('direction_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzsport.directioneffect', verbose_name='Направление воздействияэффекта')),
            ],
            options={
                'verbose_name': 'Суггестивный эффект',
                'verbose_name_plural': 'Суггестивные эффекты',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wished_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzsport.track')),
            ],
            options={
                'verbose_name': 'Закладки',
                'verbose_name_plural': 'Закладки',
                'unique_together': {('user', 'wished_track')},
            },
        ),
    ]
