# Generated by Django 4.0.4 on 2022-05-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity_period', models.CharField(blank=True, max_length=20, null=True, verbose_name='Срок действия')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер заказа')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Дата заказа')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=150, null=True, verbose_name='Автор')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название трека')),
                ('sport_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Вид спорта')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('beginning_peak', models.BooleanField(default=True, verbose_name='Пик в начале')),
                ('sportsman_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя спортсмена')),
                ('photo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фото')),
                ('track_length', models.IntegerField(blank=True, null=True, verbose_name='Длительность трека')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'ordering': ['id'],
            },
        ),
    ]
