# Generated by Django 4.0.4 on 2022-07-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='tag_name',
            field=models.ManyToManyField(blank=True, null=True, to='muzsport.tags', verbose_name='Хэштег'),
        ),
    ]
