# Generated by Django 4.0.4 on 2022-06-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unloadingmodule',
            options={'verbose_name': 'Разгрузочный модуль', 'verbose_name_plural': 'Разгрузочный модуль'},
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона'),
        ),
    ]
