# Generated by Django 4.0.4 on 2022-07-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(default=1, upload_to='mp4', verbose_name='Трэк'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='track_images/', verbose_name='Фото'),
        ),
    ]
