# Generated by Django 4.0.4 on 2022-07-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0002_alter_track_file_alter_track_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackmodification',
            name='composition',
            field=models.CharField(choices=[('auto', 'Авто'), ('manual', 'Ручная')], default='auto', max_length=20, verbose_name='Компоновка'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_length',
            field=models.TimeField(blank=True, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='trackmodification',
            name='end',
            field=models.CharField(choices=[('smooth', 'Плавное'), ('sharp', 'Резкое')], default='smooth', max_length=20, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='trackmodification',
            name='order_segment_add',
            field=models.ManyToManyField(blank=True, null=True, to='muzsport.ordersegmentadd', verbose_name='Добавление сегмента'),
        ),
        migrations.AlterField(
            model_name='trackmodification',
            name='order_segment_delete',
            field=models.ManyToManyField(blank=True, null=True, to='muzsport.ordersegmentdelete', verbose_name='Удаление сегмента'),
        ),
    ]
