# Generated by Django 4.0.4 on 2022-07-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0002_alter_track_file_alter_track_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceModificationAndServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_finished_track', models.IntegerField(max_length=30, verbose_name='Цена доработки трека')),
                ('price_additional_track', models.IntegerField(max_length=30, verbose_name='Цена добавления трека к программе')),
                ('price_suggestive_effect', models.IntegerField(max_length=30, verbose_name='Цена суггестивного эффекта')),
                ('price_unloading_module', models.IntegerField(max_length=30, verbose_name='Цена разгрузочного модуля')),
                ('sports_programme_min', models.IntegerField(max_length=30, verbose_name='Цена спортивной программы(минимальный тариф)')),
                ('sports_programme_medium', models.IntegerField(max_length=30, verbose_name='Цена спортивной программы(средний тариф)')),
                ('sports_programme_max', models.IntegerField(max_length=30, verbose_name='Цена спортивной программы(максимальный тариф)')),
            ],
            options={
                'verbose_name': 'Цены доработок и услуг',
                'verbose_name_plural': 'Цены доработок и услуг',
            },
        ),
    ]
