# Generated by Django 4.0.4 on 2022-05-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0002_alter_coupons_options_order_email_order_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['order_number'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='coupons',
            name='status',
            field=models.CharField(choices=[('Active', 'Активен'), ('Disable', 'Не активен')], default='Active', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Performed', 'Выполнен'), ('Process', 'В обработке')], default='Process', max_length=64, verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='track',
            name='direction_of_effect',
            field=models.CharField(choices=[('Concentration', 'На концетрацию'), ('Stamina', 'На выносливость'), ('Force', 'На силу и преодоление')], default=1, max_length=64, verbose_name='Направление воздействия эффекта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='end',
            field=models.CharField(choices=[('Smooth', 'Плавное'), ('Sharp', 'Резкое')], default=1, max_length=32, verbose_name='Окончание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Номер заказа'),
            preserve_default=False,
        ),
    ]
