# Generated by Django 4.0.4 on 2022-06-19 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0002_alter_unloadingmodule_options_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='beginning_peak',
        ),
        migrations.RemoveField(
            model_name='order',
            name='comment_for_product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ending',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_auto_layout',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_begin',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_end',
        ),
        migrations.AddField(
            model_name='order',
            name='track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='muzsport.track', verbose_name='Трек'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersegmentadd',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='muzsport.order', verbose_name='Заказ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersegmentdelete',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='muzsport.order', verbose_name='Заказ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestiveeffect',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='muzsport.order', verbose_name='Заказ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='variants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='muzsport.track', verbose_name='Версии песни'),
        ),
        migrations.AddField(
            model_name='unloadingmodule',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='muzsport.order', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
