# Generated by Django 4.0.4 on 2022-05-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0003_alter_order_options_remove_order_id_coupons_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страны',
                'verbose_name_plural': 'Страна',
            },
        ),
        migrations.CreateModel(
            name='Moods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Настроение')),
            ],
            options={
                'verbose_name': 'Настроения',
                'verbose_name_plural': 'Настроение',
            },
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Наименование спорта')),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Виды спорта',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Хэштег')),
            ],
            options={
                'verbose_name': 'Хэштеги',
                'verbose_name_plural': 'Хэштег',
            },
        ),
        migrations.AlterModelOptions(
            name='coupons',
            options={'verbose_name': 'Купон', 'verbose_name_plural': 'Купоны'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='track',
            name='beginning_peak',
        ),
        migrations.RemoveField(
            model_name='track',
            name='direction_of_effect',
        ),
        migrations.RemoveField(
            model_name='track',
            name='end',
        ),
        migrations.RemoveField(
            model_name='track',
            name='sport_name',
        ),
        migrations.RemoveField(
            model_name='track',
            name='sportsman_name',
        ),
        migrations.AddField(
            model_name='coupons',
            name='coupon_name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Купон'),
        ),
        migrations.AddField(
            model_name='coupons',
            name='percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Процент'),
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='трэк'),
        ),
        migrations.AddField(
            model_name='track',
            name='with_words',
            field=models.BooleanField(default=False, verbose_name='Со словами?'),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='validity_period',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия'),
        ),
        migrations.AddField(
            model_name='track',
            name='country_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='muzsport.country', verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='mood_name',
            field=models.ManyToManyField(to='muzsport.moods', verbose_name='Настроение'),
        ),
        migrations.AddField(
            model_name='track',
            name='sports_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='muzsport.sports', verbose_name='Наименование спорта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='tag_name',
            field=models.ManyToManyField(to='muzsport.tags', verbose_name='Хэштег'),
        ),
    ]
