# Generated by Django 4.0.4 on 2022-07-07 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0003_pricemodificationandservices'),
        ('muzsport', '0003_trackmodification_composition_and_more'),
    ]

    operations = [
    ]
