# Generated by Django 4.0.4 on 2022-06-22 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0003_remove_order_beginning_peak_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название способа оплаты')),
                ('icon', models.ImageField(upload_to='payment_icons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Способы оплаты(иконки)',
                'verbose_name_plural': 'Способы оплаты(иконки)',
            },
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Закладка', 'verbose_name_plural': 'Закладки'},
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время оформления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='track',
        ),
        migrations.AddField(
            model_name='order',
            name='track',
            field=models.ManyToManyField(to='muzsport.track', verbose_name='Заказ трека'),
        ),
        migrations.RemoveField(
            model_name='track',
            name='variants',
        ),
        migrations.AddField(
            model_name='track',
            name='variants',
            field=models.ManyToManyField(blank=True, null=True, to='muzsport.track', verbose_name='Версии песни'),
        ),
        migrations.CreateModel(
            name='TrackModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name='Начало хронометража')),
                ('time_stop', models.TimeField(verbose_name='Конец хронометража')),
                ('beginning_peak', models.BooleanField(verbose_name='Пик в начале')),
                ('end', models.BooleanField(verbose_name='Окончание')),
                ('commentary', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Комментарий к заказу')),
                ('order_segment_add', models.ManyToManyField(to='muzsport.ordersegmentadd', verbose_name='Добавление сегмента')),
                ('order_segment_delete', models.ManyToManyField(to='muzsport.ordersegmentdelete', verbose_name='Удаление сегмента')),
                ('sports_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzsport.sports', verbose_name='Вид спорта')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzsport.track', verbose_name='Трек')),
            ],
            options={
                'verbose_name': 'Доработать трек',
                'verbose_name_plural': 'Доработать трек',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_count_start', models.IntegerField(default=2021, null=True, verbose_name='С какого года')),
                ('year_count_end', models.IntegerField(default=2022, null=True, verbose_name='По какой год')),
                ('link_icon', models.BooleanField(default=True, verbose_name='Отображение иконки со ссылкой')),
                ('payment_icons', models.ManyToManyField(to='muzsport.paymenticons', verbose_name='Способы оплаты')),
            ],
            options={
                'verbose_name': 'Футер',
                'verbose_name_plural': 'Футеры',
            },
        ),
        migrations.CreateModel(
            name='CustomTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name='Начало хронометража')),
                ('time_stop', models.TimeField(verbose_name='Конец хронометража')),
                ('beginning_peak', models.BooleanField(verbose_name='Пик в начале')),
                ('end', models.BooleanField(verbose_name='Окончание')),
                ('link', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на файл')),
                ('file', models.FileField(blank=True, null=True, upload_to='mp4', verbose_name='Файл (MP3)')),
                ('commentary', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Комментарий к заказу')),
                ('order_segment_add', models.ManyToManyField(to='muzsport.ordersegmentadd', verbose_name='Добавление сегмента')),
                ('order_segment_delete', models.ManyToManyField(to='muzsport.ordersegmentdelete', verbose_name='Удаление сегмента')),
                ('sports_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzsport.sports', verbose_name='Вид спорта')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzsport.track', verbose_name='Трек из каталога')),
            ],
            options={
                'verbose_name': 'Индивидуальный трек',
                'verbose_name_plural': 'Индивидуальные треки',
            },
        ),
        migrations.CreateModel(
            name='AddTrackToTheProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на файл')),
                ('file', models.FileField(blank=True, null=True, upload_to='mp4', verbose_name='Файл (MP3)')),
                ('commentary', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Комментарий к заказу')),
                ('order_segment_add', models.ManyToManyField(to='muzsport.ordersegmentadd', verbose_name='Добавление сегмента')),
                ('order_segment_delete', models.ManyToManyField(to='muzsport.ordersegmentdelete', verbose_name='Удаление сегмента')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzsport.track', verbose_name='Трек из каталога')),
            ],
            options={
                'verbose_name': 'Добавить трек к программе',
                'verbose_name_plural': 'Добавить трек к программе',
            },
        ),
    ]
