# Generated by Django 4.0.4 on 2022-07-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0004_merge_20220708_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtracktotheprogram',
            name='composition',
            field=models.CharField(choices=[('auto', 'Авто'), ('manual', 'Ручная')], default='auto', max_length=20, verbose_name='Компоновка'),
        ),
        migrations.AddField(
            model_name='trackmodification',
            name='additional_tracks',
            field=models.ManyToManyField(blank=True, null=True, to='muzsport.addtracktotheprogram', verbose_name='Доп. треки к программе'),
        ),
        migrations.AlterField(
            model_name='addtracktotheprogram',
            name='order_segment_add',
            field=models.ManyToManyField(blank=True, null=True, to='muzsport.ordersegmentadd', verbose_name='Добавление сегмента'),
        ),
        migrations.AlterField(
            model_name='addtracktotheprogram',
            name='order_segment_delete',
            field=models.ManyToManyField(blank=True, null=True, to='muzsport.ordersegmentdelete', verbose_name='Удаление сегмента'),
        ),
    ]
