# Generated by Django 4.0.4 on 2022-05-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0004_country_moods_sports_tags_alter_coupons_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='mp4', verbose_name='Трэк'),
        ),
    ]
