# Generated by Django 4.0.4 on 2022-05-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0005_alter_track_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='photo',
            field=models.ImageField(default=123, upload_to='track_images/'),
            preserve_default=False,
        ),
    ]
