# Generated by Django 4.0.4 on 2022-07-07 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0005_addtracktotheprogram_composition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtracktotheprogram',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='muzsport.track', verbose_name='Трек из каталога'),
        ),
    ]
