# Generated by Django 4.0.4 on 2022-05-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0006_alter_country_options_alter_moods_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='track',
            name='photo',
            field=models.ImageField(default=1, upload_to='track_images/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
