# Generated by Django 4.0.4 on 2022-07-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0006_alter_addtracktotheprogram_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackmodification',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
