# Generated by Django 4.0.4 on 2022-07-08 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0007_trackmodification_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtracktotheprogram',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='muzsport.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='addtracktotheprogram',
            name='track_modification',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='muzsport.trackmodification', verbose_name='Доработка трека'),
        ),
        migrations.AddField(
            model_name='order',
            name='track_custom',
            field=models.ManyToManyField(to='muzsport.customtrack', verbose_name='Индивидуальный заказ трека'),
        ),
        migrations.AddField(
            model_name='order',
            name='track_modification',
            field=models.ManyToManyField(to='muzsport.trackmodification', verbose_name='Доработка трека'),
        ),
        migrations.AddField(
            model_name='suggestiveeffect',
            name='track_modification',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='muzsport.trackmodification', verbose_name='Доработка трека'),
        ),
        migrations.AddField(
            model_name='trackmodification',
            name='suggestive_effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='muzsport.suggestiveeffect', verbose_name='Суггестивный эффект'),
        ),
        migrations.AlterField(
            model_name='suggestiveeffect',
            name='direction_effect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzsport.directioneffect', verbose_name='Направление воздействия эффекта'),
        ),
        migrations.AlterField(
            model_name='suggestiveeffect',
            name='order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='muzsport.order', verbose_name='Заказ'),
        ),
    ]
