# Generated by Django 4.0.4 on 2022-06-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0007_order_products_alter_track_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSegmentAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_add_begin', models.FloatField(blank=True, null=True, verbose_name='Начало хронометража')),
                ('time_add_end', models.FloatField(blank=True, null=True, verbose_name='Конец хронометража')),
                ('time_insert', models.FloatField(blank=True, null=True, verbose_name='Вставить в')),
            ],
            options={
                'verbose_name': 'Таймер добавления',
                'verbose_name_plural': 'Таймеры добавлений',
            },
        ),
        migrations.CreateModel(
            name='OrderSegmentDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_delete_begin', models.TimeField(blank=True, null=True, verbose_name='Начало хронометража')),
                ('time_delete_end', models.FloatField(blank=True, null=True, verbose_name='Конец хронометража')),
            ],
            options={
                'verbose_name': 'Таймер удаления',
                'verbose_name_plural': 'Таймеры удалений',
            },
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Хэштег', 'verbose_name_plural': 'Хэштеги'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='beginning_peak',
            field=models.BooleanField(default=1, verbose_name='Пик в начале'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='comment_for_product',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Коментарий к продукту'),
        ),
        migrations.AddField(
            model_name='order',
            name='ending',
            field=models.BooleanField(default=1, verbose_name='Окончание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_auto_layout',
            field=models.BooleanField(default=1, verbose_name='Автоматическа компоновка?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='time_begin',
            field=models.FloatField(blank=True, null=True, verbose_name='Начало хронометража'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_end',
            field=models.FloatField(blank=True, null=True, verbose_name='Конец хронометража'),
        ),
    ]
