# Generated by Django 4.0.4 on 2022-06-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0008_ordersegmentadd_ordersegmentdelete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ending',
            field=models.BooleanField(verbose_name='Окончание плавное'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_begin',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало хронометража'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец хронометража'),
        ),
        migrations.AlterField(
            model_name='ordersegmentadd',
            name='time_add_begin',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало хронометража'),
        ),
        migrations.AlterField(
            model_name='ordersegmentadd',
            name='time_add_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец хронометража'),
        ),
        migrations.AlterField(
            model_name='ordersegmentadd',
            name='time_insert',
            field=models.TimeField(blank=True, null=True, verbose_name='Вставить в'),
        ),
        migrations.AlterField(
            model_name='ordersegmentdelete',
            name='time_delete_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец хронометража'),
        ),
    ]
