# Generated by Django 4.0.4 on 2022-06-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0009_alter_order_ending_alter_order_time_begin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBigPhotoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='ad_big_photo_images/', verbose_name='Фото')),
                ('ad_period', models.DateField(blank=True, null=True, verbose_name='Срок рекламы')),
                ('published', models.BooleanField(verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Большая реклама',
                'verbose_name_plural': 'Большие рекламы',
            },
        ),
        migrations.CreateModel(
            name='AdSmallPhotoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='ad_small_photo_images/', verbose_name='Фото')),
                ('ad_period', models.DateField(blank=True, null=True, verbose_name='Срок рекламы')),
                ('published', models.BooleanField(verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Маленькая реклама',
                'verbose_name_plural': 'Маленькие рекламы',
            },
        ),
    ]
