# Generated by Django 4.0.4 on 2022-07-08 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0009_alter_suggestiveeffect_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackmodification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='muzsport.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='addtracktotheprogram',
            name='order_segment_add',
            field=models.ManyToManyField(blank=True, to='muzsport.ordersegmentadd', verbose_name='Добавление сегмента'),
        ),
        migrations.AlterField(
            model_name='addtracktotheprogram',
            name='order_segment_delete',
            field=models.ManyToManyField(blank=True, to='muzsport.ordersegmentdelete', verbose_name='Удаление сегмента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='track_modification',
            field=models.ManyToManyField(related_name='track_modifications', to='muzsport.trackmodification', verbose_name='Доработка трека'),
        ),
        migrations.AlterField(
            model_name='pricemodificationandservices',
            name='price_additional_track',
            field=models.IntegerField(verbose_name='Цена добавления трека к программе'),
        ),
        migrations.AlterField(
            model_name='pricemodificationandservices',
            name='price_finished_track',
            field=models.IntegerField(verbose_name='Цена доработки трека'),
        ),
        migrations.AlterField(
            model_name='pricemodificationandservices',
            name='price_suggestive_effect',
            field=models.IntegerField(verbose_name='Цена суггестивного эффекта'),
        ),
        migrations.AlterField(
            model_name='pricemodificationandservices',
            name='price_unloading_module',
            field=models.IntegerField(verbose_name='Цена разгрузочного модуля'),
        ),
        migrations.AlterField(
            model_name='pricemodificationandservices',
            name='sports_programme_max',
            field=models.IntegerField(verbose_name='Цена спортивной программы(максимальный тариф)'),
        ),
        migrations.AlterField(
            model_name='pricemodificationandservices',
            name='sports_programme_medium',
            field=models.IntegerField(verbose_name='Цена спортивной программы(средний тариф)'),
        ),
        migrations.AlterField(
            model_name='pricemodificationandservices',
            name='sports_programme_min',
            field=models.IntegerField(verbose_name='Цена спортивной программы(минимальный тариф)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='tag_name',
            field=models.ManyToManyField(blank=True, to='muzsport.tags', verbose_name='Хэштег'),
        ),
        migrations.AlterField(
            model_name='track',
            name='variants',
            field=models.ManyToManyField(blank=True, to='muzsport.track', verbose_name='Версии песни'),
        ),
        migrations.AlterField(
            model_name='trackmodification',
            name='additional_tracks',
            field=models.ManyToManyField(blank=True, to='muzsport.addtracktotheprogram', verbose_name='Доп. треки к программе'),
        ),
        migrations.AlterField(
            model_name='trackmodification',
            name='order_segment_add',
            field=models.ManyToManyField(blank=True, to='muzsport.ordersegmentadd', verbose_name='Добавление сегмента'),
        ),
        migrations.AlterField(
            model_name='trackmodification',
            name='order_segment_delete',
            field=models.ManyToManyField(blank=True, to='muzsport.ordersegmentdelete', verbose_name='Удаление сегмента'),
        ),
    ]
