# Generated by Django 4.0.4 on 2022-07-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0010_trackmodification_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestiveeffect',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на файл'),
        ),
    ]
