# Generated by Django 4.0.4 on 2022-06-11 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muzsport', '0010_adbigphotofile_adsmallphotofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wished_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzsport.track')),
            ],
            options={
                'verbose_name': 'Закладки',
                'verbose_name_plural': 'Закладки',
                'unique_together': {('user', 'wished_track')},
            },
        ),
    ]
