# Generated by Django 4.0.4 on 2022-06-16 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muzsport', '0011_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_effect_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Направление воздействияэффекта')),
            ],
            options={
                'verbose_name': 'Направление воздействия эффекта',
                'verbose_name_plural': 'Направления воздействий эффектов',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='comment_for_product',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий к продукту'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_auto_layout',
            field=models.BooleanField(verbose_name='Автоматическая компоновка?'),
        ),
        migrations.CreateModel(
            name='UnloadingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ссылка на файл')),
                ('file', models.FileField(blank=True, null=True, upload_to='mp4', verbose_name='Дополнительный файл')),
                ('direction_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzsport.directioneffect', verbose_name='Направление воздействияэффекта')),
            ],
            options={
                'verbose_name': 'Суггестивный эффект',
                'verbose_name_plural': 'Суггестивные эффекты',
            },
        ),
        migrations.CreateModel(
            name='SuggestiveEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя спортсмена')),
                ('file', models.FileField(blank=True, null=True, upload_to='mp4', verbose_name='Дополнительный файл')),
                ('direction_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muzsport.directioneffect', verbose_name='Направление воздействияэффекта')),
            ],
            options={
                'verbose_name': 'Суггестивный эффект',
                'verbose_name_plural': 'Суггестивные эффекты',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.BooleanField(default=False, verbose_name='Подписан?')),
                ('subscription_email', models.EmailField(blank=True, max_length=256, null=True, verbose_name='Почта подписки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
