# Generated by Django 4.0.4 on 2022-07-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0012_alter_track_track_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(max_length=5000, upload_to='mp4', verbose_name='Трэк'),
        ),
    ]
