# Generated by Django 4.0.4 on 2022-07-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0012_alter_track_track_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_length',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Длительность'),
        ),
    ]
