# Generated by Django 4.0.4 on 2022-07-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0013_alter_track_file'),
        ('muzsport', '0013_alter_track_track_length'),
    ]

    operations = [
    ]
