# Generated by Django 4.0.4 on 2022-07-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0014_merge_20220715_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='track',
            field=models.ManyToManyField(blank=True, to='muzsport.track', verbose_name='Заказ трека'),
        ),
        migrations.AlterField(
            model_name='order',
            name='track_custom',
            field=models.ManyToManyField(blank=True, to='muzsport.customtrack', verbose_name='Индивидуальный заказ трека'),
        ),
        migrations.AlterField(
            model_name='order',
            name='track_modification',
            field=models.ManyToManyField(blank=True, related_name='track_modifications', to='muzsport.trackmodification', verbose_name='Доработка трека'),
        ),
    ]
