# Generated by Django 4.0.4 on 2022-07-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0014_merge_20220716_1624'),
        ('muzsport', '0015_alter_order_track_alter_order_track_custom_and_more'),
    ]

    operations = [
    ]
