# Generated by Django 4.0.4 on 2022-07-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0016_merge_20220720_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='direction_music',
            field=models.ManyToManyField(related_name='dir', to='muzsport.directionmusic', verbose_name='Направление музыки'),
        ),
    ]
