# Generated by Django 4.0.4 on 2022-08-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0017_alter_track_direction_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Страна(EN)'),
        ),
        migrations.AddField(
            model_name='directioneffect',
            name='direction_effect_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Направление воздействияэффекта(EN)'),
        ),
        migrations.AddField(
            model_name='directionmusic',
            name='direction_music_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Направление музыки(EN)'),
        ),
        migrations.AddField(
            model_name='moods',
            name='mood_name_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Настроение(EN)'),
        ),
        migrations.AddField(
            model_name='sports',
            name='sports_name_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Наименование спорта(EN)'),
        ),
        migrations.AddField(
            model_name='tags',
            name='tag_name_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Хэштег(EN)'),
        ),
    ]
