# Generated by Django 4.0.4 on 2022-08-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzsport', '0018_country_country_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='track',
            field=models.ManyToManyField(blank=True, to='muzsport.track', verbose_name='Трек из каталога'),
        ),
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(max_length=5000, upload_to='mp4', verbose_name='Трек'),
        ),
    ]
